# MongoDB setup
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

# 1 run the following to have mongoDB running
# docker-compose -f "docker-compose.yml" up -d --build

# 2 run the following to stop mongoDB from running
# docker-compose -f "docker-compose.yml" down
